package markups;

public enum VacancyKeyboardKey {
    SETTING_KEYBOARD,
    UTC_KEYBOARD,
    REGION_KEYBOARD,
    MIN_EXPERIENCE_KEYBOARD,
    MIN_SALARY_KEYBOARD,
    KEY_WORD_KEYBOARD,
    NOTIFY_TIME_KEYBOARD,
    READY_KEYBOARD,
    STOP_KEYBOARD,
    YES_OR_NO_KEYBOARD,
    START_KEYBOARD,
    START_AND_STOP_KEYBOARD,
    ROUTER_MENU_KEYBOARD,
    NONE
}
