package vacancy_tracker.core;

public enum UserSettingState {
    NOT_INITIALIZED,
    WAITING_SET_UTC,
    WAITING_SET_REGION,
    WAITING_SET_MIN_EXPERIENCE,
    WAITING_SET_MIN_SALARY,
    WAITING_SET_KEYWORD,
    WAITING_SET_NOTIFY_TIME,
    WAITING_READY_COMMAND,
    WAITING_STOP_COMMAND,
    WAITING_HOME_COMMAND,
    READY,
    CLEAN
}
